version: 2

builds:
  - main: ./cmd/lambda
    env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/spacelift-io"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath, -v]
    goos: [linux]
    goarch: [amd64, arm64]
    binary: bootstrap

archives:
  - formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

changelog:
  use: github-native
