version: 2

builds:
  - main: ./cmd/lambda
    id: lambda
    env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/spacelift-io"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath, -v]
    goos: [linux]
    goarch: [amd64, arm64]
    binary: bootstrap
  - main: ./cmd/azurefunc
    id: azurefunc
    env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/spacelift-io"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath, -v]
    goos: [linux]
    goarch: [amd64, arm64]
    binary: bootstrap
  - main: ./cmd/cloudrun
    id: cloudrun
    env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/spacelift-io"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath, -v]
    goos: [linux]
    goarch: [amd64, arm64]
    binary: autoscaler

archives:
  - id: lambda
    ids: [lambda]
    formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  - id: azurefunc
    ids: [azurefunc]
    formats: [zip]
    name_template: '{{ .ProjectName }}_azurefunc_{{ .Os }}_{{ .Arch }}'
  - id: cloudrun
    ids: [cloudrun]
    formats: [tar.gz]
    name_template: '{{ .ProjectName }}_cloudrun_{{ .Os }}_{{ .Arch }}'

changelog:
  use: github-native
