// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	computepb "cloud.google.com/go/compute/apiv1/computepb"

	mock "github.com/stretchr/testify/mock"
)

// MockGCPInstances is an autogenerated mock type for the GCPInstances type
type MockGCPInstances struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockGCPInstances) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInstance provides a mock function with given fields: ctx, project, zone, instanceName
func (_m *MockGCPInstances) GetInstance(ctx context.Context, project string, zone string, instanceName string) (*computepb.Instance, error) {
	ret := _m.Called(ctx, project, zone, instanceName)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *computepb.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*computepb.Instance, error)); ok {
		return rf(ctx, project, zone, instanceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *computepb.Instance); ok {
		r0 = rf(ctx, project, zone, instanceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*computepb.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, project, zone, instanceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGCPInstances creates a new instance of MockGCPInstances. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCPInstances(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCPInstances {
	mock := &MockGCPInstances{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
