// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	computepb "cloud.google.com/go/compute/apiv1/computepb"

	mock "github.com/stretchr/testify/mock"
)

// MockGCPCompute is an autogenerated mock type for the GCPCompute type
type MockGCPCompute struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockGCPCompute) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInstance provides a mock function with given fields: ctx, project, location, igmName, instanceURL
func (_m *MockGCPCompute) DeleteInstance(ctx context.Context, project string, location string, igmName string, instanceURL string) error {
	ret := _m.Called(ctx, project, location, igmName, instanceURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, project, location, igmName, instanceURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetInstanceGroupManager provides a mock function with given fields: ctx, project, location, name
func (_m *MockGCPCompute) GetInstanceGroupManager(ctx context.Context, project string, location string, name string) (*computepb.InstanceGroupManager, error) {
	ret := _m.Called(ctx, project, location, name)

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceGroupManager")
	}

	var r0 *computepb.InstanceGroupManager
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*computepb.InstanceGroupManager, error)); ok {
		return rf(ctx, project, location, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *computepb.InstanceGroupManager); ok {
		r0 = rf(ctx, project, location, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*computepb.InstanceGroupManager)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, project, location, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListManagedInstances provides a mock function with given fields: ctx, project, location, name
func (_m *MockGCPCompute) ListManagedInstances(ctx context.Context, project string, location string, name string) ([]*computepb.ManagedInstance, error) {
	ret := _m.Called(ctx, project, location, name)

	if len(ret) == 0 {
		panic("no return value specified for ListManagedInstances")
	}

	var r0 []*computepb.ManagedInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*computepb.ManagedInstance, error)); ok {
		return rf(ctx, project, location, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []*computepb.ManagedInstance); ok {
		r0 = rf(ctx, project, location, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*computepb.ManagedInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, project, location, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResizeIGM provides a mock function with given fields: ctx, project, location, name, newSize
func (_m *MockGCPCompute) ResizeIGM(ctx context.Context, project string, location string, name string, newSize int64) error {
	ret := _m.Called(ctx, project, location, name, newSize)

	if len(ret) == 0 {
		panic("no return value specified for ResizeIGM")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) error); ok {
		r0 = rf(ctx, project, location, name, newSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockGCPCompute creates a new instance of MockGCPCompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCPCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCPCompute {
	mock := &MockGCPCompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
