// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	azsecrets "github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets"

	mock "github.com/stretchr/testify/mock"
)

// MockAzureKeyVault is an autogenerated mock type for the AzureKeyVault type
type MockAzureKeyVault struct {
	mock.Mock
}

// GetSecret provides a mock function with given fields: ctx, secretName
func (_m *MockAzureKeyVault) GetSecret(ctx context.Context, secretName string) (azsecrets.GetSecretResponse, error) {
	ret := _m.Called(ctx, secretName)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 azsecrets.GetSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (azsecrets.GetSecretResponse, error)); ok {
		return rf(ctx, secretName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) azsecrets.GetSecretResponse); ok {
		r0 = rf(ctx, secretName)
	} else {
		r0 = ret.Get(0).(azsecrets.GetSecretResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, secretName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAzureKeyVault creates a new instance of MockAzureKeyVault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAzureKeyVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAzureKeyVault {
	mock := &MockAzureKeyVault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
