// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	armcompute "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v6"

	mock "github.com/stretchr/testify/mock"
)

// MockAzureCompute is an autogenerated mock type for the AzureCompute type
type MockAzureCompute struct {
	mock.Mock
}

// DeleteVMScaleSetVM provides a mock function with given fields: ctx, resourceGroupName, vmScaleSetName, instanceID
func (_m *MockAzureCompute) DeleteVMScaleSetVM(ctx context.Context, resourceGroupName string, vmScaleSetName string, instanceID string) error {
	ret := _m.Called(ctx, resourceGroupName, vmScaleSetName, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVMScaleSetVM")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, resourceGroupName, vmScaleSetName, instanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetVMScaleSet provides a mock function with given fields: ctx, resourceGroupName, vmScaleSetName
func (_m *MockAzureCompute) GetVMScaleSet(ctx context.Context, resourceGroupName string, vmScaleSetName string) (*armcompute.VirtualMachineScaleSet, error) {
	ret := _m.Called(ctx, resourceGroupName, vmScaleSetName)

	if len(ret) == 0 {
		panic("no return value specified for GetVMScaleSet")
	}

	var r0 *armcompute.VirtualMachineScaleSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*armcompute.VirtualMachineScaleSet, error)); ok {
		return rf(ctx, resourceGroupName, vmScaleSetName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *armcompute.VirtualMachineScaleSet); ok {
		r0 = rf(ctx, resourceGroupName, vmScaleSetName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*armcompute.VirtualMachineScaleSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, resourceGroupName, vmScaleSetName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVMScaleSetVM provides a mock function with given fields: ctx, resourceGroupName, vmScaleSetName, instanceID
func (_m *MockAzureCompute) GetVMScaleSetVM(ctx context.Context, resourceGroupName string, vmScaleSetName string, instanceID string) (*armcompute.VirtualMachineScaleSetVM, error) {
	ret := _m.Called(ctx, resourceGroupName, vmScaleSetName, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for GetVMScaleSetVM")
	}

	var r0 *armcompute.VirtualMachineScaleSetVM
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*armcompute.VirtualMachineScaleSetVM, error)); ok {
		return rf(ctx, resourceGroupName, vmScaleSetName, instanceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *armcompute.VirtualMachineScaleSetVM); ok {
		r0 = rf(ctx, resourceGroupName, vmScaleSetName, instanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*armcompute.VirtualMachineScaleSetVM)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, resourceGroupName, vmScaleSetName, instanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListVMScaleSetVMs provides a mock function with given fields: ctx, resourceGroupName, vmScaleSetName
func (_m *MockAzureCompute) ListVMScaleSetVMs(ctx context.Context, resourceGroupName string, vmScaleSetName string) ([]*armcompute.VirtualMachineScaleSetVM, error) {
	ret := _m.Called(ctx, resourceGroupName, vmScaleSetName)

	if len(ret) == 0 {
		panic("no return value specified for ListVMScaleSetVMs")
	}

	var r0 []*armcompute.VirtualMachineScaleSetVM
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*armcompute.VirtualMachineScaleSetVM, error)); ok {
		return rf(ctx, resourceGroupName, vmScaleSetName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*armcompute.VirtualMachineScaleSetVM); ok {
		r0 = rf(ctx, resourceGroupName, vmScaleSetName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*armcompute.VirtualMachineScaleSetVM)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, resourceGroupName, vmScaleSetName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVMScaleSetCapacity provides a mock function with given fields: ctx, resourceGroupName, vmScaleSetName, capacity
func (_m *MockAzureCompute) UpdateVMScaleSetCapacity(ctx context.Context, resourceGroupName string, vmScaleSetName string, capacity int64) error {
	ret := _m.Called(ctx, resourceGroupName, vmScaleSetName, capacity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVMScaleSetCapacity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, resourceGroupName, vmScaleSetName, capacity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAzureCompute creates a new instance of MockAzureCompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAzureCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAzureCompute {
	mock := &MockAzureCompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
