name: Check and Upload Go Dependency Licenses

permissions:
  contents: read

on:
  workflow_call:
  push:

jobs:
  check-go-dependency-licenses:
    name: "Check Go dependency licenses"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checkout license check action
        uses: actions/checkout@v6
        with:
          repository: spacelift-io/upload-dependencies-to-notion
          ref: main
          path: .github/actions/license-check
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with: { go-version-file: go.mod }

      - name: Check licenses
        uses: ./.github/actions/license-check/.github/actions/check-go-licenses
        with:
          package_paths: "./cmd/cloudrun ./cmd/local ./cmd/lambda ./cmd/azurefunc"

      - name: Upload to Notion
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/license-check
        with:
          package_paths: "./cmd/cloudrun ./cmd/local ./cmd/lambda ./cmd/azurefunc"
          application_name: "Workerpool Autoscaler"
          notion_root_page_id: ${{ vars.NOTION_DEPENDENCY_UPLOAD_ROOT_PAGE_ID }}
          notion_requests_per_second: "10"
          notion_upload_token: ${{ secrets.NOTION_DEPENDENCY_UPLOAD_TOKEN }}